steps:
  #step 1
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker pull gcr.io/aragon-core/notification-service:latest || exit 0'
  - name: gcr.io/cloud-builders/docker
    id: 'Build Docker Image'
    args: 
    - 'build'
    - '-t'
    - 'gcr.io/aragon-core/notification-service:$COMMIT_SHA'
    - '-t'
    - 'gcr.io/aragon-core/notification-service:latest'
    - '--cache-from'
    - 'gcr.io/aragon-core/notification-service:latest'
    - '.'
  - name: gcr.io/cloud-builders/gcloud
    id: 'Decrypt environment variables'
    args:
      - 'kms'
      - 'decrypt'
      - '--ciphertext-file=k8s/secrets.yaml.enc'
      - '--plaintext-file=k8s/secrets.yaml'
      - '--location=global'
      - '--keyring=aragon-production'
      - '--key=notification-service'
  #
  # TODO: double check that that it's a no-op if the manifests don't change
  # I suspect that because the docker image tag is not set k8s might consider
  # it "changed" and start a new pod
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Apply manifests'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      [[ "$BRANCH_NAME" == "master" ]] && /builder/kubectl.bash apply -f k8s/ || echo "Skipping deployment for non-master branches"
  # Set new image tag
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      [[ "$BRANCH_NAME" == "master" ]] && /builder/kubectl.bash set image deployment notification-service notification-service=gcr.io/aragon-core/notification-service:$COMMIT_SHA || echo "Skipping deployment for non-master branches"
# push images to Google Container Registry with tags
images:
  [
    'gcr.io/aragon-core/notification-service:$COMMIT_SHA',
    'gcr.io/aragon-core/notification-service:latest',
  ]
