steps:
  #step 1
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker pull gcr.io/aragon-core/notification-service:latest || exit 0'
  - name: gcr.io/cloud-builders/docker
    id: 'Build Docker Image'
    args: 
    - 'build'
    - '-t'
    - 'gcr.io/aragon-core/notification-service:$COMMIT_SHA'
    - '-t'
    - 'gcr.io/aragon-core/notification-service:latest'
    - '--cache-from'
    - 'gcr.io/aragon-core/notification-service:latest'
    - '.'
  - name: gcr.io/cloud-builders/gcloud
    id: 'Decrypt environment variables'
    args:
      - 'kms'
      - 'decrypt'
      - '--ciphertext-file=k8s/secrets.yaml.enc'
      - '--plaintext-file=k8s/secrets.yaml'
      - '--location=global'
      # Vars in Cloud Build substitution variables
      - '--keyring=$_KEYRING'
      - '--key=$_KEY'
  #
  # TODO: double check that that it's a no-op if the manifests don't change
  # I suspect that because the docker image tag is not set k8s might consider
  # it "changed" and start a new pod
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Apply manifests'
    args: ['apply', '-f', 'k8s/']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'
  # Set new image tag
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment'
      - 'notification-service'
      - 'notification-service=gcr.io/aragon-core/notification-service:$COMMIT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'
# push images to Google Container Registry with tags
images:
  [
    'gcr.io/aragon-core/notification-service:$COMMIT_SHA',
    'gcr.io/aragon-core/notification-service:latest',
  ]
