apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
  name: notification-service-http-errors
spec:
  groups:
    - name: aragon
      rules:
        - alert: NotificationServiceHttp4xxError
          annotations:
            message: Notification service HTTP 4xx errors rate spike
          expr: sum(rate(http_requests_total{service=~"notification-service", status_code=~"4.."}[1m])) > 2
          for: 2m
          labels:
            severity: critical
        - alert: NotificationServiceHttp5xxError
          annotations:
            message: Notification service HTTP 4xx errors rate spike
          expr: sum(rate(http_requests_total{service=~"notification-service", status_code=~"5.."}[1m])) > 2
          for: 2m
          labels:
            severity: critical
