apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  NODE_ENV: "production"
  METRICS_PORT: "5001"
  PORT: "5000"
  HOST: "0.0.0.0"
  ETH_NODE_RINKEBY: "wss://rinkeby.eth.aragon.network/ws"
  ETH_NODE_MAINNET: "wss://mainnet.eth.aragon.network/ws"
  IPFS_NODE: "ipfs.eth.aragon.network"
  DEBUG_KNEX: "true"
  CLIENT_URL: "https://mainnet.aragon.org"