apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: gcr.io/aragon-core/notification-service:latest
        ports:
        - containerPort: 5000
        - containerPort: 5001
        env:
        - name: NODE_ENV
          value: "production"
        - name: METRICS_PORT
          value: "5001"
        - name: PORT
          value: "5000"
        - name: HOST
          value: "0.0.0.0"
        - name: ETH_NODE
          value: "wss://rinkeby.eth.aragon.network/ws"
        - name: IPFS_NODE
          value: "ipfs.eth.aragon.network"
        - name: DEBUG_KNEX
          value: "true"
        envFrom:
        - secretRef:
           name: notification-service-secrets

