apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: gcr.io/aragon-core/notification-service:latest
        ports:
        - containerPort: 5000
        - containerPort: 5001
        env:
        - name: NODE_ENV
          value: "production"
        - name: METRICS_PORT
          value: "5001"
        - name: PORT
          value: "5000"
        - name: HOST
          value: "0.0.0.0"
        - name: ETH_NODE
          value: "wss://rinkeby.eth.aragon.network/ws"
        - name: IPFS_NODE
          value: "ipfs.eth.aragon.network"
        - name: DEBUG_KNEX
          value: "true"
        - name: EXTERNAL_URL
          value: "https://notifications.eth.aragon.network"
        envFrom:
        - secretRef:
           name: notification-service-secrets
      # Sidecar container to proxy traffic to cloud SQL
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.14
        command: ["/cloud_sql_proxy",
                  "-instances=aragon-core:us-central1:aragon-postgres=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
