{
 "title": "Notification Service",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "label": "service", "query": "notification-service" },
   {
    "name": "route",
    "label": "Route",
    "query": "label_values(http_request_duration_seconds_count{service=~\"$service\"}, path)"
   },
   {
    "name": "status_code",
    "label": "Status Code",
    "query": "label_values(http_request_duration_seconds_count{service=~\"$service\", path=\"$route\"}, status_code)"
   }
  ]
 },
 "panels": [
  { "title": "Notification Scanner", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "calls to getPastLogs in the last 5 minutes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(notification_scanner_get_past_logs_total[5m])"
    }
   ]
  },
  {
   "title": "Scanned  Contracts in the last five minutes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(notification_scanner_scanned_contracts[5m]))"
    }
   ]
  },
  {
   "title": "notifications queued for sending in db in last 5 minutes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(notification_scanner_notifications_created_total[5m])"
    }
   ]
  },
  {
   "title": "Scans per minute",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(notification_scanner_runs_total[1m]))"
    }
   ]
  },
  {
   "title": "notifications sent via postmark in last 5 minutes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(notificatios_emails_sent_total[5m])"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Requests per status code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code)(increase(http_requests_total{service=\"notification-service\", path!=\"/healthz\"}[5m]))\n\n  "
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (irate(http_requests_total{service=~\"$service\",path!=\"/healthz\", status_code=~\"$status_code\"}[1m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request latency (per route)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{service=~\"$service\", path=~\"$route\", status_code=~\"$status_code\"}[1m])) by (le))",
     "legendFormat": "Request latency - 90th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{service=~\"$service\", path=~\"$route\", status_code=~\"$status_code\"}[1m])) by (le))",
     "legendFormat": "Request latency - 95th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{service=~\"$service\", path=~\"$route\", status_code=~\"$status_code\"}[1m])) by (le))",
     "legendFormat": "Request latency - 99th percentile"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "DB Error Rate ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "irate(db_error_total[1m])", "legendFormat": "Error Rate" }
   ]
  },
  {
   "title": "Web3 Error Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "irate(web3_error_total[1m])" }
   ]
  },
  {
   "title": "API HTTP 5xx Error Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path)(rate(http_requests_total{service=\"$service\", path!=\"/healthz\", status_code=~\"5..\"}[1m]))"
    }
   ]
  },
  { "title": "Memory / CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Total Allocated Heap Size (bytes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_size_total_bytes{service=~\"$service\"}",
     "legendFormat": "Heap Size Allocated {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total{service=~\"$service\"}[30s])",
     "legendFormat": "CPU Usage {{pod}}"
    }
   ]
  },
  {
   "title": "Heap Usage From Total Allocated (bytes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_size_used_bytes{service=~\"$service\"}",
     "legendFormat": "Heap Size Used {{instance}}"
    }
   ]
  }
 ]
}